<a href="https://colab.research.google.com/github/KevinCandra9999/colab-test/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.tensor ([1,2,3])
x

tensor([1, 2, 3])

In [5]:
y = torch.tensor ([
    [1,2,3],
    [2,3,4],
    [0,0,0]
], dtype=torch.float)
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [7]:
torch.ones (1, 2, dtype=torch.int)

tensor([[1, 1]], dtype=torch.int32)

In [9]:
torch.zeros (5, 3, 2, dtype=torch.float)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [12]:
z = torch.rand(3,4, 2, dtype=torch.float)
z

tensor([[[0.8405, 0.7302],
         [0.5336, 0.9259],
         [0.8437, 0.3948],
         [0.8207, 0.7532]],

        [[0.6985, 0.3861],
         [0.6271, 0.2913],
         [0.2585, 0.9532],
         [0.5338, 0.9386]],

        [[0.8739, 0.3802],
         [0.3102, 0.3426],
         [0.9795, 0.8858],
         [0.4318, 0.5524]]])

In [13]:
print(y)
y[0]

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


tensor([1., 2., 3.])

In [15]:
y[:, 1]

tensor([2., 3., 0.])

In [16]:
z[2, :, 0]

tensor([0.8739, 0.3102, 0.9795, 0.4318])

In [17]:
y.size()

torch.Size([3, 3])

In [18]:
y.size()[0]

3

In [21]:
t = torch.rand (3, 3)
t

tensor([[0.4965, 0.1512, 0.3482],
        [0.4877, 0.4352, 0.2458],
        [0.4969, 0.3601, 0.2409]])

In [22]:
y + t

tensor([[1.4965, 2.1512, 3.3482],
        [2.4877, 3.4352, 4.2458],
        [0.4969, 0.3601, 0.2409]])

In [23]:
y * 3

tensor([[ 3.,  6.,  9.],
        [ 6.,  9., 12.],
        [ 0.,  0.,  0.]])

In [24]:
print(y)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


In [25]:
y.reshape(1, 9)

tensor([[1., 2., 3., 2., 3., 4., 0., 0., 0.]])

In [27]:
y.reshape(-1, )

tensor([1., 2., 3., 2., 3., 4., 0., 0., 0.])

In [28]:
torch.squeeze(y.reshape(1, 9))

tensor([1., 2., 3., 2., 3., 4., 0., 0., 0.])

In [30]:
 y.sum(0)

tensor([3., 5., 7.])

In [31]:
torch.max(y)

tensor(4.)

In [32]:
print(y)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


In [35]:
values, indices = torch.max(y,1)
print(values)
print(indices)

tensor([3., 4., 0.])
tensor([2, 2, 0])


In [46]:
y [0, 0] == 1

tensor(True)

In [48]:
y.numpy()

array([[1., 2., 3.],
       [2., 3., 4.],
       [0., 0., 0.]], dtype=float32)

In [49]:
import numpy as np

a = np.array ([[1,2], [3,4]])
b = torch.from_numpy(a)
b

tensor([[1, 2],
        [3, 4]])

In [52]:
a[0, 0] = 2
a

array([[2, 2],
       [3, 4]])

In [53]:
b

tensor([[2, 2],
        [3, 4]])