<a href="https://colab.research.google.com/github/KevinCandra9999/colab-test/blob/main/notebooks/GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
a = torch.rand(3, 3)
a

tensor([[0.9806, 0.0065, 0.8125],
        [0.5670, 0.8465, 0.1035],
        [0.3858, 0.0450, 0.0079]])

In [ ]:
b = torch.rand(3, 3).to(device)
b

tensor([[0.1562, 0.7440, 0.0968],
        [0.3841, 0.8274, 0.1248],
        [0.4645, 0.1722, 0.5838]], device='cuda:0')

In [ ]:
c = torch.rand(3,3).cuda()
c

tensor([[0.0015, 0.7212, 0.2059],
        [0.8384, 0.1358, 0.7634],
        [0.0848, 0.9728, 0.4569]], device='cuda:0')

In [ ]:
import time

In [ ]:
start = time.time()
a = torch.ones(400,400)
for _ in range(10000):
  a += a
duration = time.time() - start
print(f'CPU time: {duration}')


start = time.time()
b = torch.ones(400,400).to(device)
for _ in range(10000):
  b += b
duration = time.time() - start
print(f'GPU time: {duration}')

CPU time: 0.2381455898284912
GPU time: 0.060050010681152344
